-- Schema changes live in supabase/migrations.
-- Run each file once, in filename order, in the Supabase SQL editor.
-- Do not edit a file after it has been applied. Add a new timestamped file instead.
